name: track
version: "v0.0.1"
shortDescription: "CLI plugin which allows to database entities in hasura"
homepage: https://github.com/scriptonist/hasura-cli-track
hidden: true
platforms:
  - uri: "https://github.com/scriptonist/hasura-cli-track/releases/download/v0.0.1/hasura-cli-track-linux-amd64.tar.gz"
    sha256: "855ab90940cf2d9796aeab7a9964521e99caada9e5eaaa60be9c83531a0649d4"
    bin: hasura-track
    files:
      - from: ./hasura-cli-track-linux-amd64
        to: hasura-track
    selector: linux-amd64
  - uri: "https://github.com/scriptonist/hasura-cli-track/releases/download/v0.0.1/hasura-cli-track-macos-amd64.tar.gz"
    sha256: "1ce9f1e0889edc9eacfef296d3648d29d8ec69fc23b40bcb3772e99e25e9e19b"
    bin: hasura-track
    files:
      - from: ./hasura-cli-track-macos-amd64
        to: hasura-track
    selector: darwin-amd64
  - uri: "https://github.com/scriptonist/hasura-cli-track/releases/download/v0.0.1/hasura-cli-track-windows-amd64.exe.zip"
    sha256: "1941d44b7ea4ebb5bc45e012fc2793bc743e18cd642984dba126b4cf8e979a7f"
    bin: hasura-track.exe
    files:
      - from: ./hasura-cli-track-windows-amd64.exe
        to: hasura-track.exe
    selector: windows-amd64
